language: rust
rust: nightly

script:
  - cargo test --no-default-features --features "W32 L4 P1"
  - cargo test --no-default-features --features "W32 L6 P1"
  - cargo test --no-default-features --features "W64 L4 P1"
  - cargo test --no-default-features --features "W64 L4 P4"
  - cargo test --no-default-features --features "W64 L6 P1"
  - cd permutation
  - cargo test --no-default-features --features "W8  L4"
  - cargo test --no-default-features --features "W16 L4"
  - cargo test --no-default-features --features "W32 L4"
  - cargo test --no-default-features --features "W32 L6"
  - cargo test --no-default-features --features "W64 L4"
  - cargo test --no-default-features --features "W64 L6"
  - # TODO simd test
  - # env RUSTFLAGS="-C target-cpu=native" cargo test --no-default-features --features "simd W32 L4"
  - # env RUSTFLAGS="-C target-cpu=native" cargo test --no-default-features --features "simd W32 L6"
  - # env RUSTFLAGS="-C target-cpu=native" cargo test --no-default-features --features "simd W64 L4"
  - # env RUSTFLAGS="-C target-cpu=native" cargo test --no-default-features --features "simd W64 L6"

cache: cargo
