[package]
name = "norx-permutation"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
coresimd = { git = "https://github.com/rust-lang-nursery/stdsimd", optional = true }

[features]
default = [ "config_644" ]
simd = [ "coresimd" ]
config_084 = []
config_164 = []
config_324 = []
config_326 = []
config_644 = []
config_646 = []
